### ISSUE TITLE
[Feat] 세션 중 각 포인트에 대한 정보 레이아웃

### ISSUE THREAD

**Issue by Taerogrammer** [DeveloperAcademy-POSTECH/MacC-Team-DGC#112]
## 이슈 요약

> 해당 이슈가 어떤 이슈인지에 대한 간략한 설명을 추가합니다.

- 세션 중일 때 나타나는 맵뷰에서 버튼을 클릭 시 해당 지점에 대한 정보를 나타내는 뷰입니다.

## 체크리스트

> 이슈에 관련된 요구사항이나 확인해야할 사항이 있으면 추가합니다.

- [ ] 하단 레이아웃 설정
- [ ] 각각의 버튼 클릭 가능하게 설정
- [ ] 버튼 클릭 시, 해당 지점에 대한 정보 나타내기

## 참고자료

> 해당 이슈를 해결하기 위해 참고해야할 자료가 있다면 추가합니다.

🔗 [링크](url)

## 기타 (스크린샷 등)

> 이슈에 대한 이해를 돕기 위한 자료가 있다면 추가합니다.

<img width="791" alt="image" src="https://github.com/DeveloperAcademy-POSTECH/MacC-Team-DGC/assets/104834390/caf05dc1-25fb-450d-b49a-ca61e546bfbc">

**Comment by zhunhe** [comment]
이어서 작업하겠습니닷! 🫡

**Comment by Taerogrammer** [comment]
ㅋㅋ 넵 !

**Comment by zhunhe** [comment]
#102 와 같은 내용이므로 클로즈 하겠습니다
