### ISSUE TITLE
[Fix] iPhone 8일 때의 Constraint 수정

### ISSUE THREAD

**Issue by Taerogrammer** [DeveloperAcademy-POSTECH/MacC-Team-DGC#339]
## 이슈 요약

> 해당 이슈가 어떤 이슈인지에 대한 간략한 설명을 추가합니다.

- iPhone 8일 때 보이지 않는 컴포넌트에 관해 Constraint를 수정하는 이슈입니다.

## 체크리스트

> 이슈에 관련된 요구사항이나 확인해야할 사항이 있으면 추가합니다.

- [ ] 요일 반복될 때 일요일 안보이는 부분
- [ ] 컬렉션 뷰 Footer 잘리는 부분

## 참고자료

> 해당 이슈를 해결하기 위해 참고해야할 자료가 있다면 추가합니다.

🔗 [링크](url)

## 기타 (스크린샷 등)

> 이슈에 대한 이해를 돕기 위한 자료가 있다면 추가합니다.

[요일 반복될 때 일요일 안보이는 부분 해결]

<img width="300" alt="image" src="https://github.com/DeveloperAcademy-POSTECH/MacC-Team-DGC/assets/104834390/0e652f94-e122-4785-8844-08bfecd60f2a">

<br>
<br>

[컬렉션 뷰 Footer 잘리는 부분]

<img width="300" alt="image" src="https://github.com/DeveloperAcademy-POSTECH/MacC-Team-DGC/assets/104834390/0d69f107-bbbc-4e1d-9232-daadec83a2e1">

**Comment by kybeen** [comment]
셀 개수가 1개 더 있는 것 같슴다

![IMG_6084](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-DGC/assets/89764127/26db9e00-7ab9-445f-acd0-0da73b9e47fc)
