### ISSUE TITLE
[HOTFIX] ‼️초대코드 입력 시 크루 데이터 잘못 들어가는 문제

### ISSUE THREAD

**Issue by kybeen** [DeveloperAcademy-POSTECH/MacC-Team-DGC#354]
## 이슈 요약

> 해당 이슈가 어떤 이슈인지에 대한 간략한 설명을 추가합니다.

### ‼️ 초대코드를 입력해서 크루를 들어갈 때 크루 데이터가 이상하게 바뀌는 문제가 있어서 수정이 필요합니다.
- 초대코드를 입력하고 크루에 들어가면 동승자가 선택한 경유지에 크루의 데이터가 또 들어가는 문제가 있습니다.
  <img width="264" alt="스크린샷 2023-11-27 오전 2 44 54" src="https://github.com/DeveloperAcademy-POSTECH/MacC-Team-DGC/assets/89764127/ec857fb5-a2be-45a3-8ddc-84fc033fd3b7">
- 이렇게 들어온 후 크루 나가기를 누르면 동승자가 나간 포인트의 데이터에 크루 이름밖에 남지 않는 문제가 있습니다.
  <img width="297" alt="스크린샷 2023-11-27 오전 2 51 07" src="https://github.com/DeveloperAcademy-POSTECH/MacC-Team-DGC/assets/89764127/7ca5bdc2-8039-4aff-8364-50b47e38b191">

## 체크리스트

> 이슈에 관련된 요구사항이나 확인해야할 사항이 있으면 추가합니다.

- [ ] 요구사항 1
- [ ] 요구사항 2

## 참고자료

> 해당 이슈를 해결하기 위해 참고해야할 자료가 있다면 추가합니다.

🔗 [링크](url)

## 기타 (스크린샷 등)

> 이슈에 대한 이해를 돕기 위한 자료가 있다면 추가합니다.

**Comment by Taerogrammer** [comment]
해당 이슈 제가 가져가겠슴다~!
