### ISSUE TITLE
[Feat] 친구 추가 기능 구현

### ISSUE THREAD

**Issue by kybeen** [DeveloperAcademy-POSTECH/MacC-Team-DGC#58]
## 이슈 요약

> 해당 이슈가 어떤 이슈인지에 대한 간략한 설명을 추가합니다.

파이어베이스와 연동하여 친구 추가 기능을 구현합니다.

## 체크리스트

> 이슈에 관련된 요구사항이나 확인해야할 사항이 있으면 추가합니다.

- [ ] 친구 없을 때 뷰 구현
- [x] 친구 목록 불러오기 구현
  - [x] 친구 닉네임 셀에 반영
  - [x] 친구 프로필 이미지 셀에 반영
- [x] 친구 상세 페이지 정보 넘겨주기
  - [ ] 친구 삭제 기능 구현
- [x] 유저(친구) 검색 구현
- [x] 친구 요청 보내기
- [ ] 친구 요청 수락
- [ ] 회원 탈퇴 시 해당 유저의 친구 관계도 모두 삭제

## 참고자료

> 해당 이슈를 해결하기 위해 참고해야할 자료가 있다면 추가합니다.

🔗 [링크](url)

## 기타 (스크린샷 등)

> 이슈에 대한 이해를 돕기 위한 자료가 있다면 추가합니다.

**Comment by zhunhe** [comment]
친구 목록 불러오는 작업 가져와서 진행하겠습니다 !

**Comment by kybeen** [comment]
> 유저 검색하는 기능 진행하겠습니다 !

작업 제가 다시 회수해가도록 하겠습니다😇
